Update recive_sms

diff --git a/recive_sms b/recive_sms
--- a/recive_sms
+++ b/recive_sms
@@ -1,26 +1,31 @@
 #!/bin/sh
-LTEPROTO=$(cat /etc/config/network | grep -E "proto 'qmi'|proto 'mbim'" | wc -l)
-if [ ${LTEPROTO} -eq "1" ]; then
-sms_tool -d /dev/ttyUSB2 -s SM status
-sms_tool -d /dev/ttyUSB2 -s ME status
-sms_tool -d /dev/ttyUSB2 -s SR status
-sms_tool -d /dev/ttyUSB2 -s MT status
-sms_tool -d /dev/ttyUSB2 recv
-read -n1 -p "you want to delete all SMS [y,n] " question
-if [ ${question} == "y" ]; then
-echo
-echo "delete all SMS"
-sms_tool -d /dev/ttyUSB2 delete all >/dev/null 2>&1
-#echo 0 > /sys/class/leds/green:voice/brightness
-else
-echo
-echo "no delete SMS"
-fi
 
-#uqmi -d /dev/cdc-wdm0 --list-messages
-#uqmi -d /dev/cdc-wdm0 --list-messages --storage me
-#uqmi -d /dev/cdc-wdm0 --get-message 0
-#uqmi -d /dev/cdc-wdm0 --get-message 0 --storage me
-#uqmi -d /dev/cdc-wdm0 --delete-message 0
-#uqmi -d /dev/cdc-wdm0 --delete-message 0 --storage me
+deletesms(){
+printf "\ndelete all SMS\n"
+sms_tool -d /dev/ttyUSB2 delete all >/dev/null 2>&1
+echo 0 > /sys/class/leds/green:voice/brightness
+}
+
+nodeletesms(){
+printf "\nno delete SMS\n"
+}
+
+lteproto=$(cat /etc/config/network | grep -c "proto 'modemmanager'")
+if [ "$lteproto" -eq "0" ]; then
+    sms_tool -d /dev/ttyUSB2 -s SM status
+    sms_tool -d /dev/ttyUSB2 -s ME status
+    sms_tool -d /dev/ttyUSB2 -s SR status
+    sms_tool -d /dev/ttyUSB2 -s MT status
+    sms_tool -d /dev/ttyUSB2 recv
+
+    printf "you want to delete all SMS [y,n]\n"
+    read -r -n1 question
+    case "$question" in
+    y*|Y*) deletesms ;;
+    n*|N*) nodeletesms ;;
+    *) printf "invalid option\n"; exit 1;;
+    esac
+else
+    printf "Script not compatible with \"ModemManager\"\n"
+    exit 1
 fi
